# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc039b0f41fe2b1715bfb61d3137f25f0dc6c669b4db080faf7ee722563410e7094c9b79df9b1933713702752c3b46766d3641410814390626cf92a1b977ae7c

test:
  secret_key_base: 92439544c0ed72fc288a93e1bcc1b3ee71e4b27ec36511ab40b5b7c359811db95a0c1cf96bac2aedb391be53114073ffc01bb42494d8fc43e9973016c16efbb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
